[project]
name = "band-monitor-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.116.1",
    "playwright>=1.54.0",
    "uvicorn>=0.35.0",
    "redis>=5.0.0",
]
